/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GimnacioGUI;

import GimnacioClase.ClaseGimnasio;
import GimnacioCliente.Cliente;
import GimnacioInfraestructura.FachadaGimnasio;
import GimnacioInfraestructura.FabricaRepositorios;
import GimnacioInfraestructura.TipoRepositorio;
import GimnacioClienteClase.ClienteClase;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luisf
 */
public class ClaseCliente extends javax.swing.JInternalFrame {

    private FachadaGimnasio facade;
    private List<Cliente> clientes;
    private List<ClaseGimnasio> clases;
    private DefaultListModel<String> modeloListaClasesCliente;
    private Map<String, List<ClaseGimnasio>> asignaciones;
    private Map<Long, Asignacion> asignacionesPorId = new HashMap<>();
    private long contadorIdAsignacion = 1L;

    private static class Asignacion {

        private FachadaGimnasio facade;
        private List<Cliente> clientes;
        private List<ClaseGimnasio> clases;
        private DefaultListModel<String> modeloListaClasesCliente;
    }

    public ClaseCliente() {
        initComponents();

        FabricaRepositorios fabrica = new FabricaRepositorios(TipoRepositorio.MYSQL);
        this.facade = new FachadaGimnasio(fabrica);

        this.clientes = new ArrayList<>();
        this.clases = new ArrayList<>();
        this.modeloListaClasesCliente = new DefaultListModel<>();
        this.asignaciones = new HashMap<>();

        jList1.setModel(modeloListaClasesCliente);

        jTextArea1.setEditable(false);

        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        asignarclase = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxclases = new javax.swing.JComboBox<>();
        jComboBoxcliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnBuscarAsignacion = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        txtIdAsignacion = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignación de Cliente a Clase", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        asignarclase.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        asignarclase.setText("Asignar clases");
        asignarclase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        asignarclase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarclaseActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setText("Clases asignadas al cliente: ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jList1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jScrollPane2.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Cliente:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Clases:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jComboBoxclases.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBoxclases.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jComboBoxclases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxclasesActionPerformed(evt);
            }
        });

        jComboBoxcliente.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jComboBoxcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jComboBoxcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxclienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Detalle del Cliente:");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jScrollPane1.setViewportView(jTextArea1);

        btnBuscarAsignacion.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscarAsignacion.setText("Buscar");
        btnBuscarAsignacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        btnBuscarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignacionActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ID.setText("ID:");
        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtIdAsignacion.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtIdAsignacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asignarclase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(146, 146, 146)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxclases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(ID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 494, Short.MAX_VALUE)
                                        .addComponent(btnBuscarAsignacion)))))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(txtIdAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAsignacion))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxclases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignarclase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asignarclaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarclaseActionPerformed

        asignarClaseAlCliente();
    }//GEN-LAST:event_asignarclaseActionPerformed

    private void jComboBoxclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxclienteActionPerformed

        actualizarDetalle();
        actualizarListaClasesCliente();
    }//GEN-LAST:event_jComboBoxclienteActionPerformed

    private void jComboBoxclasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxclasesActionPerformed

        actualizarDetalle();
    }//GEN-LAST:event_jComboBoxclasesActionPerformed

    private void btnBuscarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignacionActionPerformed

        buscarAsignacionPorId();
    }//GEN-LAST:event_btnBuscarAsignacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton asignarclase;
    private javax.swing.JButton btnBuscarAsignacion;
    private javax.swing.JComboBox<String> jComboBoxclases;
    private javax.swing.JComboBox<String> jComboBoxcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtIdAsignacion;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {

        clientes = facade.getServicioCliente().listarTodos();
        jComboBoxcliente.removeAllItems();
        for (Cliente c : clientes) {
            String texto = c.getCedula() + " - " + c.getNombreCompleto();
            jComboBoxcliente.addItem(texto);
        }

        clases = facade.getServicioClase().listarTodas();
        jComboBoxclases.removeAllItems();
        for (ClaseGimnasio cl : clases) {
            String texto = cl.getCodigo() + " - " + cl.getNombre() + " (" + cl.getHorario() + ")";
            jComboBoxclases.addItem(texto);
        }

        actualizarDetalle();
        actualizarListaClasesCliente();
    }

    private void actualizarDetalle() {
        Cliente clienteSeleccionado = obtenerClienteSeleccionado();
        ClaseGimnasio claseSeleccionada = obtenerClaseSeleccionada();

        StringBuilder sb = new StringBuilder();

        if (clienteSeleccionado != null) {
            sb.append("CLIENTE:\n");
            sb.append("Cédula: ").append(clienteSeleccionado.getCedula()).append("\n");
            sb.append("Nombre: ").append(clienteSeleccionado.getNombreCompleto()).append("\n");
            sb.append("Teléfono: ").append(
                    clienteSeleccionado.getTelefono() == null ? "" : clienteSeleccionado.getTelefono()
            ).append("\n\n");
        }

        if (claseSeleccionada != null) {
            sb.append("CLASE:\n");
            sb.append("Código: ").append(claseSeleccionada.getCodigo()).append("\n");
            sb.append("Nombre: ").append(claseSeleccionada.getNombre()).append("\n");
            sb.append("Horario: ").append(claseSeleccionada.getHorario()).append("\n");
        }

        jTextArea1.setText(sb.toString());
    }

    private void asignarClaseAlCliente() {
        Cliente cliente = obtenerClienteSeleccionado();
        ClaseGimnasio clase = obtenerClaseSeleccionada();

        if (cliente == null || clase == null) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un cliente y una clase.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String cedula = cliente.getCedula();
        int codigoClase = Integer.parseInt(clase.getCodigo());
        ClienteClase nuevaAsignacion = new ClienteClase();
        nuevaAsignacion.setCedulaCliente(cedula);
        nuevaAsignacion.setCodigoClase(codigoClase);

        try {

            long idGenerado = facade.getServicioClase().asignarClaseACliente(nuevaAsignacion);

            if (idGenerado > 0) {
                JOptionPane.showMessageDialog(this,
                        "Clase asignada correctamente.\nID Asignación: " + idGenerado,
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE);
                txtIdAsignacion.setText(String.valueOf(idGenerado));
                actualizarListaClasesCliente();
            } else {

                JOptionPane.showMessageDialog(this,
                        "La clase ya estaba asignada o la asignación falló.",
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (RuntimeException ex) {
            if (ex.getMessage() != null && ex.getMessage().contains("ya tiene asignada")) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {

                JOptionPane.showMessageDialog(this,
                        "Error al intentar asignar la clase: " + ex.getMessage(),
                        "Error de Persistencia",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void actualizarListaClasesCliente() {
        modeloListaClasesCliente.clear();
        Cliente cliente = obtenerClienteSeleccionado();

        if (cliente == null) {
            return;
        }

        try {

            List<ClaseGimnasio> clasesCliente = facade.getServicioClase().listarClasesAsignadasPorCliente(cliente.getCedula());

            if (clasesCliente == null || clasesCliente.isEmpty()) {
                return;
            }

            for (ClaseGimnasio cl : clasesCliente) {
                String texto = cl.getCodigo() + " - " + cl.getNombre() + " (" + cl.getHorario() + ")";
                modeloListaClasesCliente.addElement(texto);
            }
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar clases del cliente: " + ex.getMessage(),
                    "Error de Persistencia",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private Cliente obtenerClienteSeleccionado() {
        int index = jComboBoxcliente.getSelectedIndex();
        if (clientes == null || index < 0 || index >= clientes.size()) {
            return null;
        }
        return clientes.get(index);
    }

    private ClaseGimnasio obtenerClaseSeleccionada() {
        int index = jComboBoxclases.getSelectedIndex();
        if (clases == null || index < 0 || index >= clases.size()) {
            return null;
        }
        return clases.get(index);
    }

    private void buscarAsignacionPorId() {
        String textoId = txtIdAsignacion.getText().trim();

        if (textoId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Digite el ID de la asignación.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            txtIdAsignacion.requestFocus();
            return;
        }

        long id;
        try {
            id = Long.parseLong(textoId);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "El ID debe ser un número numérico válido.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            txtIdAsignacion.requestFocus();
            return;
        }

        try {

            Optional<ClienteClase> asignacionOpt = facade.getServicioClase().buscarAsignacionPorId(id);

            if (!asignacionOpt.isPresent()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró ninguna asignación con ese ID.",
                        "Sin resultados",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            ClienteClase asignacion = asignacionOpt.get();

            seleccionarClientePorCedula(asignacion.getCedulaCliente());
            seleccionarClasePorCodigo(String.valueOf(asignacion.getCodigoClase()));

            actualizarDetalle();
            actualizarListaClasesCliente();

        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al buscar la asignación: " + ex.getMessage(),
                    "Error de Persistencia",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void seleccionarClientePorCedula(String cedula) {
        if (cedula == null) {
            return;
        }
        for (int i = 0; i < clientes.size(); i++) {
            Cliente c = clientes.get(i);
            if (cedula.equals(c.getCedula())) {
                jComboBoxcliente.setSelectedIndex(i);
                break;
            }
        }
    }

    private void seleccionarClasePorCodigo(String codigoClase) {
        if (codigoClase == null) {
            return;
        }
        for (int i = 0; i < clases.size(); i++) {
            ClaseGimnasio cl = clases.get(i);
            if (codigoClase.equals(cl.getCodigo())) {
                jComboBoxclases.setSelectedIndex(i);
                break;
            }
        }
    }

}
