/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GimnacioGUI;

import GimnacioClase.ClaseGimnasioDTO;
import GimnacioClase.ClaseGimnasioMapper;
import GimnacioClase.ClaseGimnasio;
import GimnacioEntrenador.Entrenador;
import GimnacioInfraestructura.FachadaGimnasio;
import GimnacioInfraestructura.FabricaRepositorios;
import GimnacioInfraestructura.TipoRepositorio;
import javax.swing.JOptionPane;
import java.util.Optional;
import java.util.List;
import GimnacioUsuarios.RepositorioUsuarios;
import GimnacioUsuarios.RolUsuario;
import GimnacioUsuarios.Usuario;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;

/**
 *
 * @author Luisf
 */
public class Clases extends javax.swing.JInternalFrame {

    private final FachadaGimnasio facade;
    private final ClaseGimnasioMapper mapper;
    private final RepositorioUsuarios repositorioUsuarios;

    public Clases() {
        FabricaRepositorios fabrica = new FabricaRepositorios(TipoRepositorio.MYSQL);
        this.facade = new FachadaGimnasio(fabrica);
        this.mapper = new ClaseGimnasioMapper();
        this.repositorioUsuarios = fabrica.crearRepositorioUsuarios();
        initComponents();
        inicializarLogica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JFormattedTextField();
        jComboBoxentrenador = new javax.swing.JComboBox<>();
        jComboTipoClase = new javax.swing.JComboBox<>();

        jLabel1.setText("Tipo de Clase:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clases ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de Clase:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Horario:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Entrenador Asignado:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Capacidad Maxima:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_48.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leftjust.png"))); // NOI18N
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_cancel (4).png"))); // NOI18N
        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gtk-clear.png"))); // NOI18N
        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 2));

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        try {
            jTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##-##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboTipoClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTipoClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13)
                    .addComponent(jButton12)
                    .addComponent(jButton14)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarEntrenadoresEnCombo() {
        jComboBoxentrenador.removeAllItems();

        List<Entrenador> entrenadores = facade.getServicioEntrenador().listarTodos();

        if (entrenadores.isEmpty()) {
            jComboBoxentrenador.addItem("** No hay entrenadores **");
            jComboBoxentrenador.setEnabled(false);
            return;
        }

        jComboBoxentrenador.setEnabled(true);

        for (Entrenador e : entrenadores) {

            String item = e.getCedula() + " - " + e.getNombreCompleto();
            jComboBoxentrenador.addItem(item);
        }
    }

    private void inicializarLogica() {

        jComboBox2.removeAllItems();

        jComboBox2.addItem("5");
        jComboBox2.addItem("10");
        jComboBox2.addItem("15");
        jComboBox2.addItem("20");
        jComboBox2.addItem("25");
        jComboBox2.addItem("30");
        jComboBox2.addItem("35");
        jComboBox2.addItem("40");
        jComboBox2.addItem("45");
        jComboBox2.addItem("50");

        jComboTipoClase.removeAllItems();
        jComboTipoClase.addItem("Musculación");
        jComboTipoClase.addItem("Cardio");
        jComboTipoClase.addItem("Crossfit");
        jComboTipoClase.addItem("Zumba");
        jComboTipoClase.addItem("Yoga");

        jButton12.addActionListener(e -> agregar());
        jButton13.addActionListener(e -> listar());
        jButton14.addActionListener(e -> buscar());
        jButton15.addActionListener(e -> eliminar());
        jButton16.addActionListener(e -> limpiarFormulario());
        cargarEntrenadoresEnCombo();
    }

    private void agregar() {
        String nombreClase = (String) jComboTipoClase.getSelectedItem();
        if (nombreClase == null || nombreClase.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar el tipo de clase.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String horario = jTextField2.getText().trim();

        if (!horario.matches("\\d{2}:\\d{2}-\\d{2}:\\d{2}")) {
            JOptionPane.showMessageDialog(this,
                    "El horario debe tener el formato HH:MM-HH:MM, por ejemplo 09:00-11:00.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String inicioStr = horario.substring(0, 5);
        String finStr = horario.substring(6, 11);

        try {
            LocalTime horaInicio = LocalTime.parse(inicioStr);
            LocalTime horaFin = LocalTime.parse(finStr);

            if (!horaInicio.isBefore(horaFin)) {
                JOptionPane.showMessageDialog(this,
                        "La hora inicial debe ser ANTES que la hora final.\n"
                        + "Ejemplo válido: 09:00-12:00",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "Horario inválido. Use un horario válido, por ejemplo 09:00-11:00.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String entrenadorSeleccion = (String) jComboBoxentrenador.getSelectedItem();

        String cupoTexto = (String) jComboBox2.getSelectedItem();

        if (nombreClase.isEmpty() || horario.isEmpty()
                || entrenadorSeleccion == null || entrenadorSeleccion.isBlank()
                || cupoTexto == null || cupoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Todos los campos son obligatorios.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!jComboBoxentrenador.isEnabled()) {
            JOptionPane.showMessageDialog(this,
                    "No se puede registrar la clase porque no hay entrenadores registrados.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String entrenadorCedula = entrenadorSeleccion.split(" - ")[0].trim();

        List<Entrenador> entrenadores = facade.getServicioEntrenador().listarTodos();
        Entrenador entrenadorEncontrado = null;
        for (Entrenador e : entrenadores) {
            if (e.getCedula().equals(entrenadorCedula)) {
                entrenadorEncontrado = e;
                break;
            }
        }

        if (entrenadorEncontrado == null) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró el entrenador con cédula " + entrenadorCedula + ".",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String especialidad = entrenadorEncontrado.getEspecialidad();

        if (especialidad == null || !especialidad.equalsIgnoreCase(nombreClase)) {
            JOptionPane.showMessageDialog(this,
                    "El entrenador '" + entrenadorEncontrado.getNombreCompleto() + "' tiene especialidad '"
                    + especialidad + "' y no puede impartir la clase '" + nombreClase + "'.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int cupoMaximo;
        try {
            cupoMaximo = Integer.parseInt(cupoTexto);
            if (cupoMaximo <= 0) {
                throw new NumberFormatException("El cupo debe ser mayor que cero.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Capacidad máxima inválida. Debe ser un número entero positivo.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        List<ClaseGimnasio> existentes = facade.getServicioClase().listarTodas();
        String codigo = "CL-" + (existentes.size() + 1);

        ClaseGimnasioDTO dto = new ClaseGimnasioDTO(
                codigo,
                nombreClase,
                horario,
                entrenadorCedula,
                cupoMaximo
        );
        ClaseGimnasio clase = mapper.toEntity(dto);
        facade.getServicioClase().guardar(clase);

        JOptionPane.showMessageDialog(this,
                "Clase registrada correctamente con código " + codigo,
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void listar() {
        List<ClaseGimnasio> clases = facade.getServicioClase().listarTodas();
        if (clases.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay clases registradas.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        StringBuilder sb = new StringBuilder("Clases registradas:\n");
        for (ClaseGimnasio c : clases) {
            sb.append("- ")
                    .append(c.getCodigo()).append(" | ")
                    .append(c.getNombre()).append(" | ")
                    .append(c.getHorario()).append(" | entrenador: ")
                    .append(c.getEntrenadorCedula()).append(" | cupo: ")
                    .append(c.getCupoMaximo())
                    .append("\n");
        }

        JOptionPane.showMessageDialog(this,
                sb.toString(),
                "Listado de clases",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void buscar() {
        String filtro = JOptionPane.showInputDialog(this,
                "Ingrese el tipo de clase a Buscar:",
                "Buscar clases",
                JOptionPane.QUESTION_MESSAGE);
        if (filtro == null || filtro.trim().isEmpty()) {
            return;
        }

        List<ClaseGimnasio> resultados = facade.getServicioClase().buscarPorFiltro(filtro.trim());
        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontraron clases que coincidan con el filtro.",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (resultados.size() == 1) {
            ClaseGimnasio c = resultados.get(0);

            if (c.getNombre() != null) {
                boolean encontrado = false;
                for (int i = 0; i < jComboTipoClase.getItemCount(); i++) {
                    if (jComboTipoClase.getItemAt(i).equalsIgnoreCase(c.getNombre())) {
                        jComboTipoClase.setSelectedIndex(i);
                        encontrado = true;
                        break;
                    }
                }
                if (!encontrado) {

                    jComboTipoClase.addItem(c.getNombre());
                    jComboTipoClase.setSelectedItem(c.getNombre());
                }
            }

            jTextField2.setText(c.getHorario() == null ? "" : c.getHorario());

            String cedulaEnt = c.getEntrenadorCedula();
            if (cedulaEnt != null) {
                for (int i = 0; i < jComboBoxentrenador.getItemCount(); i++) {
                    String item = jComboBoxentrenador.getItemAt(i);
                    if (item.startsWith(cedulaEnt + " ")) {
                        jComboBoxentrenador.setSelectedIndex(i);
                        break;
                    }
                }
            }

            String cupoStr = String.valueOf(c.getCupoMaximo());
            if (((javax.swing.DefaultComboBoxModel<String>) jComboBox2.getModel()).getIndexOf(cupoStr) == -1) {
                jComboBox2.addItem(cupoStr);
            }
            jComboBox2.setSelectedItem(cupoStr);
        } else {
            StringBuilder sb = new StringBuilder("Resultados de la búsqueda:\n");
            for (ClaseGimnasio c : resultados) {
                sb.append("- ")
                        .append(c.getCodigo()).append(" | ")
                        .append(c.getNombre()).append(" | ")
                        .append(c.getHorario())
                        .append("\n");
            }
            JOptionPane.showMessageDialog(this,
                    sb.toString(),
                    "Varios resultados",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void eliminar() {

        String filtro = JOptionPane.showInputDialog(this,
                "Ingrese nombre de la clase a eliminar:",
                "Eliminar clase",
                JOptionPane.QUESTION_MESSAGE);

        if (filtro == null || filtro.trim().isEmpty()) {
            return;
        }

        filtro = filtro.trim();

        try {

            List<ClaseGimnasio> resultados = facade.getServicioClase().buscarPorFiltro(filtro);

            if (resultados.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron clases que coincidan con el filtro.",
                        "Sin resultados",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (resultados.size() > 1) {
                StringBuilder sb = new StringBuilder("Se encontraron varias clases. Por favor, refine su búsqueda con el **código** exacto:\n\n");
                for (ClaseGimnasio c : resultados) {
                    sb.append("- **Código**: ").append(c.getCodigo())
                            .append(" | Tipo: ").append(c.getNombre())
                            .append(" | Horario: ").append(c.getHorario())
                            .append("\n");
                }

                JOptionPane.showMessageDialog(this,
                        sb.toString(),
                        "Resultados Múltiples",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            ClaseGimnasio claseAEliminar = resultados.get(0);

            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de eliminar la clase:\n"
                    + "Código: " + claseAEliminar.getCodigo() + "\n"
                    + "Tipo: " + claseAEliminar.getNombre() + "?",
                    "Confirmar Eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            facade.getServicioClase().eliminar(claseAEliminar.getCodigo());

            JOptionPane.showMessageDialog(this,
                    "Clase con código '" + claseAEliminar.getCodigo() + "' eliminada correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al eliminar la clase: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarFormulario() {
        if (jComboTipoClase.getItemCount() > 0) {
            jComboTipoClase.setSelectedIndex(0);
        }
        jTextField2.setText("");

        if (jComboBoxentrenador.getItemCount() > 0) {
            jComboBoxentrenador.setSelectedIndex(0);
        }
        if (jComboBox2.getItemCount() > 0) {
            jComboBox2.setSelectedIndex(0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxentrenador;
    private javax.swing.JComboBox<String> jComboTipoClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
