/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GimnacioGUI;

import GimnacioEntrenador.EntrenadorDTO;
import GimnacioEntrenador.EntrenadorMapper;
import GimnacioEntrenador.Entrenador;
import GimnacioInfraestructura.FachadaGimnasio;
import GimnacioInfraestructura.FabricaRepositorios;
import GimnacioInfraestructura.TipoRepositorio;
import javax.swing.JOptionPane;
import java.util.Optional;
import java.util.List;
import GimnacioUsuarios.Usuario;
import GimnacioUsuarios.RolUsuario;

/**
 *
 * @author Eduard Salas Murillo
 */
public class Entrenadores extends javax.swing.JInternalFrame {

    private final FachadaGimnasio facade;
    private final EntrenadorMapper mapper;

    public Entrenadores() {
        FabricaRepositorios fabrica = new FabricaRepositorios(TipoRepositorio.MYSQL);
        this.facade = new FachadaGimnasio(fabrica);
        this.mapper = new EntrenadorMapper();
        initComponents();
        inicializarLogica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        choice1 = new java.awt.Choice();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JFormattedTextField();

        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrenadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ID:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Contacto:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Especialidades:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Nombre:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_48.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leftjust.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_cancel (4).png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gtk-clear.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 2));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        try {
            jTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarLogica() {

        jComboBox2.removeAllItems();
        jComboBox2.addItem("Musculación");
        jComboBox2.addItem("Cardio");
        jComboBox2.addItem("Crossfit");
        jComboBox2.addItem("Zumba");
        jComboBox2.addItem("Yoga");

        jButton8.addActionListener(e -> agregar());
        jButton9.addActionListener(e -> listar());
        jButton10.addActionListener(e -> buscar());
        jButton11.addActionListener(e -> eliminar());
        jButton12.addActionListener(e -> limpiarFormulario());
    }

    private void agregar() {
        String cedula = jTextField1.getText().trim();
        String nombre = jTextField2.getText().trim();
        String telefono = jFormattedTextField2.getText().trim();
        String especialidad = (String) jComboBox2.getSelectedItem();

        if (cedula.isEmpty() || nombre.isEmpty() || telefono.isEmpty() || especialidad == null || especialidad.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Todos los campos son obligatorios.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            Optional<Usuario> usuarioOpt = facade.getRepositorioUsuarios().buscarPorNombreUsuario(nombre);

            if (usuarioOpt.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró un usuario registrado con la cédula " + cedula + ". El entrenador debe ser un usuario registrado.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            Usuario usuario = usuarioOpt.get();
            if (usuario.getRolUsuario() != RolUsuario.ENTRENADOR) {
                JOptionPane.showMessageDialog(this,
                        "Solo se puede asignar a usuarios con rol ENTRENADOR. Usuario "
                        + usuario.getNombreUsuario() + " es " + usuario.getRolUsuario(),
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            EntrenadorDTO dto = new EntrenadorDTO(
                    cedula,
                    nombre,
                    telefono,
                    especialidad,
                    true
            );
            Entrenador entrenador = mapper.toEntity(dto);
            facade.getServicioEntrenador().guardar(entrenador);

            JOptionPane.showMessageDialog(this,
                    "Entrenador guardado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar el entrenador: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado al buscar el usuario o guardar el entrenador: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void listar() {
        java.util.List<Entrenador> entrenadores = facade.getServicioEntrenador().listarTodos();
        if (entrenadores.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay entrenadores registrados.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        StringBuilder sb = new StringBuilder("Entrenadores registrados:\n");
        for (Entrenador e : entrenadores) {
            sb.append("- ")
                    .append(e.getCedula()).append(" | ")
                    .append(e.getNombreCompleto()).append(" | ")
                    .append(e.getTelefono()).append(" | ")
                    .append(e.getEspecialidad())
                    .append("\n");
        }

        JOptionPane.showMessageDialog(this,
                sb.toString(),
                "Listado de entrenadores",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void buscar() {
        String filtro = JOptionPane.showInputDialog(this,
                "Ingrese cédula, nombre o especialidad para buscar:",
                "Buscar entrenadores",
                JOptionPane.QUESTION_MESSAGE);
        if (filtro == null || filtro.trim().isEmpty()) {
            return;
        }

        List<Entrenador> resultados = facade.getServicioEntrenador().buscarPorFiltro(filtro.trim());
        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontraron entrenadores que coincidan con el filtro.",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (resultados.size() == 1) {
            Entrenador e = resultados.get(0);
            jTextField1.setText(e.getCedula());
            jTextField2.setText(e.getNombreCompleto());
            jFormattedTextField2.setText(e.getTelefono());
            if (e.getEspecialidad() != null) {
                if (((javax.swing.DefaultComboBoxModel<String>) jComboBox2.getModel())
                        .getIndexOf(e.getEspecialidad()) == -1) {
                    jComboBox2.addItem(e.getEspecialidad());
                }
                jComboBox2.setSelectedItem(e.getEspecialidad());
            }
        } else {
            StringBuilder sb = new StringBuilder("Resultados de la búsqueda:\n");
            for (Entrenador e : resultados) {
                sb.append("- ")
                        .append(e.getCedula()).append(" | ")
                        .append(e.getNombreCompleto()).append(" | ")
                        .append(e.getEspecialidad())
                        .append("\n");
            }
            JOptionPane.showMessageDialog(this,
                    sb.toString(),
                    "Varios resultados",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void eliminar() {
        String filtro = JOptionPane.showInputDialog(this,
                "Ingrese cédula, nombre o especialidad del entrenador a eliminar:",
                "Eliminar entrenador",
                JOptionPane.QUESTION_MESSAGE);

        if (filtro == null || filtro.trim().isEmpty()) {
            return;
        }

        filtro = filtro.trim();

        try {
            List<Entrenador> resultados = facade.getServicioEntrenador().buscarPorFiltro(filtro);

            if (resultados.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron entrenadores que coincidan con el filtro.",
                        "Sin resultados",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (resultados.size() > 1) {
                StringBuilder sb = new StringBuilder("Se encontraron varios entrenadores. Por favor, refine su búsqueda con la **cédula** exacta:\n\n");
                for (Entrenador e : resultados) {
                    sb.append("- Cédula: **").append(e.getCedula()).append("**")
                            .append(" | Nombre: ").append(e.getNombreCompleto())
                            .append(" | Especialidad: ").append(e.getEspecialidad())
                            .append("\n");
                }
                JOptionPane.showMessageDialog(this,
                        sb.toString(),
                        "Resultados Múltiples",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            Entrenador entrenadorAEliminar = resultados.get(0);

            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de eliminar al entrenador:\n"
                    + "Nombre: " + entrenadorAEliminar.getNombreCompleto() + "\n"
                    + "Cédula: " + entrenadorAEliminar.getCedula() + "?",
                    "Confirmar Eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }
            facade.getServicioEntrenador().eliminar(entrenadorAEliminar.getCedula());

            JOptionPane.showMessageDialog(this,
                    "Entrenador '" + entrenadorAEliminar.getNombreCompleto() + "' eliminado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al eliminar el entrenador: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    private void limpiarFormulario() {
        jTextField1.setText("");
        jTextField2.setText("");
        jFormattedTextField2.setText("");
        if (jComboBox2.getItemCount() > 0) {
            jComboBox2.setSelectedIndex(0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
