/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GimnacioGUI;

import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import GimnacioInfraestructura.FachadaGimnasio;
import GimnacioInfraestructura.FabricaRepositorios;
import GimnacioInfraestructura.TipoRepositorio;
import GimnacioCliente.Cliente;
import GimnacioMembresia.AlertaVencimientoMembresia;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JOptionPane;
import GimnacioUsuarios.Usuario;
import GimnacioUsuarios.RolUsuario;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Eduard Salas Murillo
 */
public class GYM extends javax.swing.JFrame {

    public javax.swing.JDesktopPane getDesktopPane() {
        return jDesktopPane1;
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GYM.class.getName());
    private ImageIcon fondoOriginal;
    private static final String RUTA_IMAGEN = "/img/gym.png";
    private Usuario usuarioActual;
    private AlertaVencimientoMembresia hiloAlertas;

    public GYM() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            fondoOriginal = new ImageIcon(getClass().getResource(RUTA_IMAGEN));
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
            return;
        }
        jLabel2.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                AjustarImag();
            }
        });
        iniciarHiloAlertasMembresia();
        AjustarImag();

        txtUsuiarios.setEnabled(false);
        txtEntrenadores.setEnabled(false);
        txtClases.setEnabled(false);
        txtPagos.setEnabled(false);
        txtRegistroClientes.setEnabled(false);
        txtCerrarSesion.setEnabled(false);
    }

    private void AjustarImag() {
        int ancho = jLabel2.getWidth();
        int alto = jLabel2.getHeight();

        if (fondoOriginal != null && ancho > 500 && alto > 0) {
            Image img = fondoOriginal.getImage();
            int originalAncho = fondoOriginal.getIconWidth();
            int originalAlto = fondoOriginal.getIconHeight();
            double factorEscala = Math.max((double) ancho / originalAncho, (double) alto / originalAlto);

            int nuevoAncho = (int) (originalAncho * factorEscala);
            int nuevoAlto = (int) (originalAlto * factorEscala);

            Image scaledImg = img.getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);

            jLabel2.setIcon(new ImageIcon(scaledImg));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txtUsuiarios = new javax.swing.JMenuItem();
        txtEntrenadores = new javax.swing.JMenuItem();
        txtClases = new javax.swing.JMenuItem();
        txtPagos = new javax.swing.JMenuItem();
        txtRegistroClientes = new javax.swing.JMenuItem();
        txtClaseCliente = new javax.swing.JMenuItem();
        txtCerrarSesion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gym.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, Short.MAX_VALUE)
        );

        jMenu1.setText("Módulos");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

        txtUsuiarios.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        txtUsuiarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003.png"))); // NOI18N
        txtUsuiarios.setText("Módulo de Usuarios");
        txtUsuiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuiariosActionPerformed(evt);
            }
        });
        jMenu1.add(txtUsuiarios);

        txtEntrenadores.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        txtEntrenadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006.png"))); // NOI18N
        txtEntrenadores.setText("Módulo de Entrenadores");
        txtEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntrenadoresActionPerformed(evt);
            }
        });
        jMenu1.add(txtEntrenadores);

        txtClases.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        txtClases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/004.png"))); // NOI18N
        txtClases.setText("Módulo de Clases");
        txtClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClasesActionPerformed(evt);
            }
        });
        jMenu1.add(txtClases);

        txtPagos.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        txtPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/005.png"))); // NOI18N
        txtPagos.setText("Módulo de  Pagos");
        txtPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagosActionPerformed(evt);
            }
        });
        jMenu1.add(txtPagos);

        txtRegistroClientes.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        txtRegistroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/007.png"))); // NOI18N
        txtRegistroClientes.setText("Módulo de Clientes");
        txtRegistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroClientesActionPerformed(evt);
            }
        });
        jMenu1.add(txtRegistroClientes);

        txtClaseCliente.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        txtClaseCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/014.png"))); // NOI18N
        txtClaseCliente.setText("Módulo de asignación del Cliente a la Clase");
        txtClaseCliente.setToolTipText("");
        txtClaseCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaseClienteActionPerformed(evt);
            }
        });
        jMenu1.add(txtClaseCliente);

        txtCerrarSesion.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        txtCerrarSesion.setForeground(new java.awt.Color(153, 0, 0));
        txtCerrarSesion.setText("Cerrar Sesión");
        txtCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(txtCerrarSesion);

        jMenuBar2.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/008.png"))); // NOI18N
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuiariosActionPerformed
        for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof GimnacioGUI.Usuarios) {
                frame.toFront();
                return;
            }
        }
        GimnacioGUI.Usuarios usuariosFrame = new GimnacioGUI.Usuarios();
        jDesktopPane1.add(usuariosFrame);
        usuariosFrame.setVisible(true);
        try {
            usuariosFrame.setSelected(true);
            usuariosFrame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {

        }

        int x = (jDesktopPane1.getWidth() - usuariosFrame.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - usuariosFrame.getHeight()) / 2;
        usuariosFrame.setLocation(x, y);
    }//GEN-LAST:event_txtUsuiariosActionPerformed

    private void txtEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntrenadoresActionPerformed
        for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof GimnacioGUI.Entrenadores) {
                frame.toFront();
                return;
            }
        }

        GimnacioGUI.Entrenadores entrenadoresFrame = new GimnacioGUI.Entrenadores();

        jDesktopPane1.add(entrenadoresFrame);

        entrenadoresFrame.setVisible(true);

        try {
            entrenadoresFrame.setSelected(true);
            entrenadoresFrame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {

        }

        int x = (jDesktopPane1.getWidth() - entrenadoresFrame.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - entrenadoresFrame.getHeight()) / 2;
        entrenadoresFrame.setLocation(x, y);
    }//GEN-LAST:event_txtEntrenadoresActionPerformed

    private void txtClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClasesActionPerformed
        for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof GimnacioGUI.Clases) {
                frame.toFront();
                return;
            }
        }

        GimnacioGUI.Clases clasesFrame = new GimnacioGUI.Clases();

        jDesktopPane1.add(clasesFrame);

        clasesFrame.setVisible(true);

        try {
            clasesFrame.setSelected(true);
            clasesFrame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {

        }

        int x = (jDesktopPane1.getWidth() - clasesFrame.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - clasesFrame.getHeight()) / 2;
        clasesFrame.setLocation(x, y);
    }//GEN-LAST:event_txtClasesActionPerformed

    private void txtPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagosActionPerformed
        for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof GimnacioGUI.Pagos) {
                frame.toFront();
                return;
            }
        }

        GimnacioGUI.Pagos pagosFrame = new GimnacioGUI.Pagos();

        jDesktopPane1.add(pagosFrame);

        pagosFrame.setVisible(true);

        try {
            pagosFrame.setSelected(true);
            pagosFrame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {
        }

        int x = (jDesktopPane1.getWidth() - pagosFrame.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - pagosFrame.getHeight()) / 2;
        pagosFrame.setLocation(x, y);
    }//GEN-LAST:event_txtPagosActionPerformed

    private void txtRegistroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroClientesActionPerformed
        for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof GimnacioGUI.RegistroClientes) {
                frame.toFront();
                return;
            }
        }

        GimnacioGUI.RegistroClientes rclientesFrame = new GimnacioGUI.RegistroClientes();

        jDesktopPane1.add(rclientesFrame);

        rclientesFrame.setVisible(true);

        try {
            rclientesFrame.setSelected(true);
            rclientesFrame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {

        }

        int x = (jDesktopPane1.getWidth() - rclientesFrame.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - rclientesFrame.getHeight()) / 2;
        rclientesFrame.setLocation(x, y);
    }//GEN-LAST:event_txtRegistroClientesActionPerformed

    private void txtCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea cerrar sesión?",
                "Cerrar Sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        javax.swing.JDesktopPane desktop = this.getDesktopPane();

        if (hiloAlertas != null) {
            hiloAlertas.detener();
            hiloAlertas = null;
        }

        for (javax.swing.JInternalFrame frame : desktop.getAllFrames()) {
            frame.dispose();
        }

        txtUsuiarios.setEnabled(false);
        txtEntrenadores.setEnabled(false);
        txtClases.setEnabled(false);
        txtPagos.setEnabled(false);
        txtRegistroClientes.setEnabled(false);
        txtCerrarSesion.setEnabled(false);
        this.usuarioActual = null;
        this.setTitle("GYM");

        Login login = new Login();
        desktop.add(login);
        int x = (desktop.getWidth() - login.getWidth()) / 2;
        int y = (desktop.getHeight() - login.getHeight()) / 2;
        login.setLocation(Math.max(x, 0), Math.max(y, 0));

        login.setVisible(true);

        try {

            login.setSelected(true);

        } catch (java.beans.PropertyVetoException ex) {
        }
    }//GEN-LAST:event_txtCerrarSesionActionPerformed

    private void txtClaseClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaseClienteActionPerformed
        for (javax.swing.JInternalFrame frame : jDesktopPane1.getAllFrames()) {
            if (frame instanceof GimnacioGUI.ClaseCliente) {
                frame.toFront();
                return;
            }
        }

        GimnacioGUI.ClaseCliente ClClienteFrame = new GimnacioGUI.ClaseCliente();

        jDesktopPane1.add(ClClienteFrame);

        ClClienteFrame.setVisible(true);

        try {
            ClClienteFrame.setSelected(true);
            ClClienteFrame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {

        }

        int x = (jDesktopPane1.getWidth() - ClClienteFrame.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - ClClienteFrame.getHeight()) / 2;
        ClClienteFrame.setLocation(x, y);
    }//GEN-LAST:event_txtClaseClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            GYM ventana = new GYM();
            ventana.setVisible(true);

            Login login = new Login();
            ventana.getDesktopPane().add(login);
            login.setVisible(true);
        });
    }

    public GYM(Usuario usuarioActual) {
        this();
        this.usuarioActual = usuarioActual;
        aplicarPermisosPorRol();
        if (usuarioActual != null) {
            setTitle("GYM - Usuario: " + usuarioActual.getNombreUsuario()
                    + " (" + usuarioActual.getRolUsuario() + ")");
        }
    }

    private void iniciarHiloAlertasMembresia() {
        FabricaRepositorios fabrica = new FabricaRepositorios(TipoRepositorio.MYSQL);
        FachadaGimnasio facade = new FachadaGimnasio(fabrica);
        List<Cliente> clientes = facade.getServicioCliente().listarTodos();

        hiloAlertas = new AlertaVencimientoMembresia(
                clientes,
                5,
                30_000L,
                mensaje -> JOptionPane.showMessageDialog(this,
                        mensaje,
                        "Alerta de membresía",
                        JOptionPane.WARNING_MESSAGE)
        );
        hiloAlertas.start();
    }

    private void aplicarPermisosPorRol() {
        if (usuarioActual == null || usuarioActual.getRolUsuario() == null) {
            return;
        }

        RolUsuario rol = usuarioActual.getRolUsuario();

        txtClaseCliente.setEnabled(false);

        switch (rol) {

            case ADMINISTRADOR:

                txtUsuiarios.setEnabled(true);
                txtEntrenadores.setEnabled(true);
                txtClases.setEnabled(true);
                txtPagos.setEnabled(true);
                txtRegistroClientes.setEnabled(true);
                txtCerrarSesion.setEnabled(true);

                txtClaseCliente.setEnabled(true);
                break;

            case ENTRENADOR:

                txtUsuiarios.setEnabled(false);
                txtPagos.setEnabled(false);
                txtEntrenadores.setEnabled(true);
                txtClases.setEnabled(true);
                txtRegistroClientes.setEnabled(true);
                txtCerrarSesion.setEnabled(true);

                txtClaseCliente.setEnabled(false);
                break;

            case CAJERO:

                txtUsuiarios.setEnabled(false);
                txtEntrenadores.setEnabled(false);
                txtClases.setEnabled(false);
                txtPagos.setEnabled(true);
                txtRegistroClientes.setEnabled(true);
                txtCerrarSesion.setEnabled(true);

                txtClaseCliente.setEnabled(false);
                break;

            case RECEPCIONISTA:

                txtUsuiarios.setEnabled(false);
                txtPagos.setEnabled(false);
                txtEntrenadores.setEnabled(true);
                txtClases.setEnabled(true);
                txtRegistroClientes.setEnabled(true);
                txtCerrarSesion.setEnabled(true);

                txtClaseCliente.setEnabled(true);
                break;

            default:

                txtUsuiarios.setEnabled(false);
                txtEntrenadores.setEnabled(false);
                txtClases.setEnabled(false);
                txtPagos.setEnabled(false);
                txtRegistroClientes.setEnabled(false);
                txtCerrarSesion.setEnabled(true);

                txtClaseCliente.setEnabled(false);
                break;
        }
    }

    @Override
    public void dispose() {
        if (hiloAlertas != null) {
            hiloAlertas.detener();
        }
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem txtCerrarSesion;
    private javax.swing.JMenuItem txtClaseCliente;
    private javax.swing.JMenuItem txtClases;
    private javax.swing.JMenuItem txtEntrenadores;
    private javax.swing.JMenuItem txtPagos;
    private javax.swing.JMenuItem txtRegistroClientes;
    private javax.swing.JMenuItem txtUsuiarios;
    // End of variables declaration//GEN-END:variables
}
