/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GimnacioGUI;

import GimnacioPago.PagoDTO;
import GimnacioPago.PagoMapper;
import GimnacioPago.Pago;
import GimnacioInfraestructura.FachadaGimnasio;
import GimnacioInfraestructura.FabricaRepositorios;
import GimnacioInfraestructura.TipoRepositorio;
import javax.swing.JOptionPane;
import java.util.Optional;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JFileChooser;
import java.nio.file.Path;
import GeneradorFacturaPDF.ReportePagosPDF;
import GimnacioCliente.Cliente;

/**
 *
 * @author Sebastian
 */
public class Pagos extends javax.swing.JInternalFrame {

    private final FachadaGimnasio facade;
    private final PagoMapper mapper;

    public Pagos() {
        FabricaRepositorios fabrica = new FabricaRepositorios(TipoRepositorio.MYSQL);
        this.facade = new FachadaGimnasio(fabrica);
        this.mapper = new PagoMapper();
        initComponents();
        inicializarLogica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField3 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Pagos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nombre Cliente:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Cédula Cliente:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Fecha:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Subtotal:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Impuesto:");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Total:");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leftjust.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/okteta.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/011.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setText("  ");
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gtk-clear.png"))); // NOI18N
        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 2));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void inicializarLogica() {

        jButton3.addActionListener(e -> registrarPago());

        jButton2.addActionListener(e -> listarPagos());

        jButton5.addActionListener(e -> exportarPagosTxt());

        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                cargar();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                cargar();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                cargar();
            }

            private void cargar() {
                try {

                    String cedula = jTextField1.getText().trim();

                    if (cedula.isEmpty()) {
                        jTextField2.setText("");
                        jTextField3.setText("");
                        jFormattedTextField2.setText("");
                        jTextField4.setText("");
                        return;
                    }

                    var lista = facade.getServicioCliente().listarTodos();

                    var encontrado = lista.stream()
                            .filter(c -> c.getCedula().equalsIgnoreCase(cedula))
                            .findFirst();

                    if (encontrado.isEmpty()) {
                        jTextField2.setText("Cliente no encontrado");
                        jTextField3.setText("");
                        jFormattedTextField2.setText("");
                        jTextField4.setText("");
                        return;
                    }

                    var cliente = encontrado.get();

                    jTextField2.setText(cliente.getNombreCompleto());
                    double subtotal;

                    switch (cliente.getTipoMembresia()) {
                        case PREMIUM ->
                            subtotal = 35000;
                        case VIP ->
                            subtotal = 50000;
                        default ->
                            subtotal = 20000;
                    }

                    double impuesto = subtotal * 0.13;
                    double total = subtotal + impuesto;

                    jTextField3.setText(String.format("%.0f", subtotal));
                    jFormattedTextField2.setText(String.format("%.0f", impuesto));
                    jTextField4.setText(String.format("%.0f", total));

                } catch (Exception ex) {

                }
            }
        });
    }

    private void registrarPago() {
        try {
            String cedulaCliente = jTextField1.getText().trim();
            String textoSubtotal = jTextField3.getText().trim();
            String textoFecha = jFormattedTextField1.getText().trim();

            if (cedulaCliente.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe digitar la Cédula del cliente.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (textoSubtotal.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe digitar el subtotal del pago.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (textoFecha.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debe digitar la fecha del pago (dd-MM-yyyy).",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Optional<Cliente> clienteOpt = facade.getServicioCliente().buscarPorCedula(cedulaCliente);

            if (clienteOpt.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Cliente con cédula " + cedulaCliente + " no encontrado.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Cliente clienteActual = clienteOpt.get();

            double subtotal = Double.parseDouble(textoSubtotal);

            LocalDate fecha;
            try {
                fecha = LocalDate.parse(textoFecha,
                        java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy"));
            } catch (DateTimeParseException ex) {
                JOptionPane.showMessageDialog(this,
                        "La fecha debe tener formato dd-MM-yyyy.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            List<Pago> pagos = facade.getServicioPago().listarTodos();
            boolean pagoExistente = pagos.stream()
                    .anyMatch(p -> p.getCedulaCliente().equalsIgnoreCase(cedulaCliente)
                    && p.getFecha().equals(fecha));

            if (pagoExistente) {
                JOptionPane.showMessageDialog(this,
                        "El cliente ya tiene un pago registrado en esta fecha.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double impuesto = subtotal * 0.13;
            double total = subtotal + impuesto;

            jFormattedTextField2.setText(String.format("%.0f", impuesto));
            jTextField4.setText(String.format("%.0f", total));

            Pago pago = new Pago();
            pago.setCedulaCliente(cedulaCliente);
            pago.setMonto(total);
            pago.setFecha(fecha);
            facade.getServicioPago().registrar(pago);

            clienteActual.setFecha(fecha.plusMonths(1));

            clienteActual.setNotificacionVencimientoMostrada(false);

            facade.getServicioCliente().guardar(clienteActual);

            JOptionPane.showMessageDialog(this,
                    "Pago registrado y membresía renovada correctamente.\n"
                    + "Subtotal: " + subtotal + "\n"
                    + "Impuesto: " + impuesto + "\n"
                    + "Total: " + total,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El subtotal debe ser un número válido.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al registrar el pago: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void listarPagos() {
        try {
            List<Pago> pagos = facade.getServicioPago().listarTodos();

            if (pagos.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No hay pagos registrados.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            StringBuilder sb = new StringBuilder();
            for (Pago p : pagos) {
                sb.append("ID: ").append(p.getId())
                        .append(" | Cliente (Cédula): ").append(p.getCedulaCliente())
                        .append(" | Fecha: ").append(p.getFecha().format(java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy")))
                        .append(" | Monto: ").append(String.format("%.2f", p.getMonto()))
                        .append("\n");
            }

            JOptionPane.showMessageDialog(this,
                    sb.toString(),
                    "Pagos registrados",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al listar los pagos: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exportarPagosTxt() {
        try {
            java.util.List<Pago> pagos = facade.getServicioPago().listarTodos();
            if (pagos.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No hay pagos para exportar.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Guardar reporte de pagos (TXT)");
            int opcion = chooser.showSaveDialog(this);
            if (opcion == JFileChooser.APPROVE_OPTION) {
                Path ruta = chooser.getSelectedFile().toPath();
                ReportePagosPDF.exportarPagos(pagos, ruta);
                JOptionPane.showMessageDialog(this,
                        "Reporte de pagos generado en:\n" + ruta,
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al exportar los pagos: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarTotal() {
        try {
            String textoSubtotal = jTextField3.getText().trim();

            if (textoSubtotal.isEmpty()) {
                jFormattedTextField2.setText("0.00");
                jTextField4.setText("0.00");
                return;
            }

            double subtotal = Double.parseDouble(textoSubtotal);

            double impuesto = subtotal * 0.13;

            double total = subtotal + impuesto;

            jFormattedTextField2.setText(String.format("%.0f", impuesto));
            jTextField4.setText(String.format("%.0f", total));

        } catch (NumberFormatException e) {

        }
    }

    private void limpiar() {
        jTextField1.setText("");
        jFormattedTextField1.setText("");
        jTextField3.setText("");
        jFormattedTextField2.setText("");
        jTextField4.setText("");
        jTextField2.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
