/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GimnacioGUI;

import GimnacioCliente.Cliente;
import GimnacioCliente.ClienteDTO;
import GimnacioCliente.ClienteMapper;
import GimnacioCliente.ServicioCliente;
import GimnacioInfraestructura.FabricaRepositorios;
import GimnacioInfraestructura.TipoRepositorio;
import GimnacioMembresia.TipoMembresia;
import static java.awt.SystemColor.desktop;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class RegistroClientes extends javax.swing.JInternalFrame {

    private final ServicioCliente servicioCliente;
    private final ClienteMapper clienteMapper;

    public RegistroClientes() {
        FabricaRepositorios fabrica = new FabricaRepositorios(TipoRepositorio.MYSQL);
        this.servicioCliente = new ServicioCliente(fabrica.crearRepositorioClientes());
        this.clienteMapper = new ClienteMapper();
        initComponents();
        inicializarLogica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Fecha Nacimiento:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Contacto:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de Membresia:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ID:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nombre:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leftjust.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_48.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_cancel (4).png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gtk-clear.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 2));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        try {
            jTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jButton11)
                    .addComponent(jButton7)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarLogica() {
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"BASICA", "PREMIUM", "VIP"}));
        jButton8.addActionListener(e -> agregarCliente());
        jButton7.addActionListener(e -> listarClientes());
        jButton9.addActionListener(e -> eliminarCliente());
        jButton10.addActionListener(e -> buscarCliente());
        jButton11.addActionListener(e -> limpiarFormulario());
    }

    private void agregarCliente() {
        try {

            String cedula = jTextField1.getText().trim();

            String nombre = jTextField2.getText().trim();

            String telefono = jFormattedTextField2.getText().trim();

            String fechaTexto = jFormattedTextField1.getText().trim();
            LocalDate fecha = null;

            if (!fechaTexto.isBlank()) {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                fecha = LocalDate.parse(fechaTexto, formatter);
            }

            String tipoStr = (String) jComboBox1.getSelectedItem();
            TipoMembresia tipo = TipoMembresia.BASICA;

            if (tipoStr != null && !tipoStr.isBlank()) {
                try {
                    tipo = TipoMembresia.valueOf(tipoStr.toUpperCase());
                } catch (Exception e) {

                }
            }

            if (cedula.isEmpty() || nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "ID y nombre son obligatorios",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (fecha == null) {
                JOptionPane.showMessageDialog(this,
                        "La fecha de nacimiento es obligatoria.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int edad = java.time.Period.between(fecha, LocalDate.now()).getYears();
            if (edad < 18) {
                JOptionPane.showMessageDialog(this,
                        "Debe tener al menos 18 años.\nEdad actual: " + edad,
                        "Restricción de edad",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (servicioCliente.buscarPorCedula(cedula).isPresent()) {
                JOptionPane.showMessageDialog(this,
                        "Ya existe un cliente con este ID.\nIngrese un ID diferente.",
                        "Duplicado",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            ClienteDTO dto = new ClienteDTO(cedula, nombre, telefono, fecha, tipo, true);
            servicioCliente.guardar(clienteMapper.toEntity(dto));

            JOptionPane.showMessageDialog(this,
                    "Cliente guardado correctamente",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void listarClientes() {
        var clientes = servicioCliente.listarTodos();
        if (clientes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay clientes registrados", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        StringBuilder sb = new StringBuilder();
        for (Cliente c : clientes) {
            sb.append(c.getCedula()).append(" - ").append(c.getNombreCompleto()).append("\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString(), "Clientes", JOptionPane.INFORMATION_MESSAGE);
    }

    private void eliminarCliente() {
        String filtro = JOptionPane.showInputDialog(this,
                "Digite el ID o nombre del cliente a eliminar:",
                "Eliminar cliente",
                JOptionPane.QUESTION_MESSAGE);

        if (filtro == null || filtro.trim().isEmpty()) {
            return;
        }

        filtro = filtro.trim();

        List<Cliente> resultados = servicioCliente.buscarPorFiltro(filtro);

        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontraron clientes que coincidan con el filtro.",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (resultados.size() > 1) {
            StringBuilder sb = new StringBuilder("Se encontraron varios clientes. Por favor, refine su búsqueda con el ID exacto:\n\n");
            for (Cliente c : resultados) {
                sb.append("- ID: ").append(c.getCedula())
                        .append(" | Nombre: ").append(c.getNombreCompleto())
                        .append(" | Tel: ").append(c.getTelefono())
                        .append("\n");
            }

            JOptionPane.showMessageDialog(this,
                    sb.toString(),
                    "Resultados Múltiples",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cliente clienteAEliminar = resultados.get(0);

        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar al cliente:\n"
                + "ID: " + clienteAEliminar.getCedula() + "\n"
                + "Nombre: " + clienteAEliminar.getNombreCompleto() + "?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {

            servicioCliente.eliminar(clienteAEliminar.getCedula());

            JOptionPane.showMessageDialog(this,
                    "Cliente '" + clienteAEliminar.getNombreCompleto() + "' eliminado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al eliminar el cliente: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarCliente() {

        String cedula = JOptionPane.showInputDialog(this,
                "Digite el ID del cliente a buscar:",
                "Buscar Cliente",
                JOptionPane.QUESTION_MESSAGE);

        if (cedula == null || cedula.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Se a cancelado la búsqueda.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        cedula = cedula.trim();

        try {

            Optional<Cliente> clienteOpt = servicioCliente.buscarPorCedula(cedula);

            if (clienteOpt.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró cliente con el ID: " + cedula,
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Cliente c = clienteOpt.get();

            jTextField1.setText(c.getCedula());
            jTextField2.setText(c.getNombreCompleto());
            jFormattedTextField2.setText(c.getTelefono());

            if (c.getFecha() != null) {
                try {
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                    jFormattedTextField1.setText(c.getFecha().format(formatter));
                } catch (Exception e) {
                    jFormattedTextField1.setText("");
                    System.err.println("Error al formatear la fecha: " + e.getMessage());
                }
            } else {
                jFormattedTextField1.setText("");
            }

            jComboBox1.setSelectedItem(
                    c.getTipoMembresia() != null
                    ? c.getTipoMembresia().name()
                    : "BASICA"
            );

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,
                    "Error al buscar cliente: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarFormulario() {
        jTextField1.setText("");
        jTextField2.setText("");
        jFormattedTextField2.setText("");

        jFormattedTextField1.setText("");

        if (jComboBox1.getItemCount() > 0) {
            jComboBox1.setSelectedIndex(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
