/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GimnacioGUI;

import GimnacioUsuarios.UsuarioDTO;
import Utils.PasswordUtils;
import GimnacioUsuarios.UsuarioMapper;
import GimnacioUsuarios.Usuario;
import GimnacioUsuarios.RepositorioUsuarios;
import GimnacioUsuarios.RolUsuario;
import GimnacioInfraestructura.FachadaGimnasio;
import GimnacioInfraestructura.FabricaRepositorios;
import GimnacioInfraestructura.TipoRepositorio;
import javax.swing.JOptionPane;
import java.util.Optional;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author USER
 */
public class Usuarios extends javax.swing.JInternalFrame {

    private final FachadaGimnasio facade;
    private final UsuarioMapper mapper;
    private final RepositorioUsuarios repositorioUsuarios;

    public Usuarios() {
        FabricaRepositorios fabrica = new FabricaRepositorios(TipoRepositorio.MYSQL);
        this.facade = new FachadaGimnasio(fabrica);
        this.mapper = new UsuarioMapper();
        this.repositorioUsuarios = fabrica.crearRepositorioUsuarios();
        initComponents();
        jFormattedTextField1.setFormatterFactory(
                new javax.swing.text.DefaultFormatterFactory(
                        new javax.swing.text.DefaultFormatter()
                )
        );

        jFormattedTextField1.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        inicializarLogica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Rol:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_48.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leftjust.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gtk-clear.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 2));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("LLLLL#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_cancel (4).png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton11)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarLogica() {

        jComboBox1.removeAllItems();
        jComboBox1.addItem(RolUsuario.ADMINISTRADOR.name());
        jComboBox1.addItem(RolUsuario.ENTRENADOR.name());
        jComboBox1.addItem(RolUsuario.CAJERO.name());
        jComboBox1.addItem(RolUsuario.RECEPCIONISTA.name());

        jButton1.addActionListener(e -> agregar());
        jButton3.addActionListener(e -> listar());
        jButton2.addActionListener(e -> buscar());
        jButton4.addActionListener(e -> limpiarFormulario());
        jButton11.addActionListener(e -> eliminar());
    }

    private void agregar() {
        String nombreUsuario = jTextField1.getText().trim();
        String contraseniaPlano = jFormattedTextField1.getText().trim();
        String rolTexto = (String) jComboBox1.getSelectedItem();

        if (nombreUsuario.isEmpty() || contraseniaPlano.isEmpty()
                || rolTexto == null || rolTexto.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Usuario, contraseña y rol son obligatorios.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        RolUsuario rol;
        try {
            rol = RolUsuario.valueOf(rolTexto);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,
                    "Rol inválido.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        Long nuevoId = 1L;
        List<Usuario> existentes = repositorioUsuarios.buscarTodos();
        if (!existentes.isEmpty()) {
            long maxId = 0L;
            for (Usuario u : existentes) {
                if (u.getId() != null && u.getId() > maxId) {
                    maxId = u.getId();
                }
            }
            nuevoId = maxId + 1;
        }

        String hash = PasswordUtils.hash(contraseniaPlano);

        UsuarioDTO dto = new UsuarioDTO(nuevoId, nombreUsuario, hash, rol);
        Usuario usuario = mapper.toEntity(dto);

        repositorioUsuarios.crear(usuario);

        JOptionPane.showMessageDialog(this,
                "Usuario creado correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void listar() {
        List<Usuario> usuarios = repositorioUsuarios.buscarTodos();
        if (usuarios.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay usuarios registrados.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        StringBuilder sb = new StringBuilder("Usuarios registrados (solo datos básicos):\n");
        for (Usuario u : usuarios) {
            sb.append("- ID: ").append(u.getId())
                    .append(" | Usuario: ").append(u.getNombreUsuario())
                    .append(" | Contraseña: ").append(u.getContrasenia())
                    .append(" | Rol: ").append(u.getRolUsuario())
                    .append("\n");
        }

        JOptionPane.showMessageDialog(this,
                sb.toString(),
                "Listado de usuarios",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void buscar() {
        String filtro = JOptionPane.showInputDialog(this,
                "Digite parte del nombre de usuario para buscar:",
                "Buscar usuarios",
                JOptionPane.QUESTION_MESSAGE);
        if (filtro == null || filtro.trim().isEmpty()) {
            return;
        }

        List<Usuario> resultados = repositorioUsuarios.buscarPorFiltro(filtro.trim());
        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontraron usuarios con ese nombre.",
                    "Sin resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (resultados.size() == 1) {
            Usuario u = resultados.get(0);
            jTextField1.setText(u.getNombreUsuario());
            jFormattedTextField1.setText("");
            if (u.getRolUsuario() != null) {
                jComboBox1.setSelectedItem(u.getRolUsuario().name());
            }
        } else {
            StringBuilder sb = new StringBuilder("Resultados:\n");
            for (Usuario u : resultados) {
                sb.append("- ID: ").append(u.getId())
                        .append(" | Usuario: ").append(u.getNombreUsuario())
                        .append(" | Contraseña: ").append(u.getContrasenia())
                        .append(" | Rol: ").append(u.getRolUsuario())
                        .append("\n");
            }
            JOptionPane.showMessageDialog(this,
                    sb.toString(),
                    "Varios resultados",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void eliminar() {
        String filtro = JOptionPane.showInputDialog(this,
                "Digite el nombre de usuario a eliminar:",
                "Eliminar Usuario",
                JOptionPane.QUESTION_MESSAGE);

        if (filtro == null || filtro.trim().isEmpty()) {
            return;
        }

        filtro = filtro.trim();

        try {

            List<Usuario> resultados = repositorioUsuarios.buscarPorFiltro(filtro);

            if (resultados.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron usuarios que coincidan con el filtro.",
                        "Sin resultados",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            if (resultados.size() > 1) {
                StringBuilder sb = new StringBuilder("Se encontraron varios usuarios. Por favor, refine su búsqueda:\n\n");
                for (Usuario u : resultados) {

                    sb.append("- ID: ").append(u.getId())
                            .append(" | Usuario: ").append(u.getNombreUsuario())
                            .append(" | Rol: ").append(u.getRolUsuario())
                            .append("\n");
                }
                JOptionPane.showMessageDialog(this,
                        sb.toString(),
                        "Resultados Múltiples",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            Usuario usuarioAEliminar = resultados.get(0);

            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de eliminar al usuario:\n"
                    + "ID: " + usuarioAEliminar.getId() + "\n"
                    + "Nombre: " + usuarioAEliminar.getNombreUsuario() + "\n"
                    + "Rol: " + usuarioAEliminar.getRolUsuario() + "?",
                    "Confirmar Eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            repositorioUsuarios.eliminar(usuarioAEliminar.getId());

            JOptionPane.showMessageDialog(this,
                    "Usuario '" + usuarioAEliminar.getNombreUsuario() + "' eliminado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Error al eliminar el usuario: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarFormulario() {
        jTextField1.setText("");
        jFormattedTextField1.setText("");
        if (jComboBox1.getItemCount() > 0) {
            jComboBox1.setSelectedIndex(0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
